//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MazzaWebSite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Business {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Business() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MazzaWebSite.Resources.Business", typeof(Business).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports Project.
        /// </summary>
        public static string BettingProject {
            get {
                return ResourceManager.GetString("BettingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon.
        /// </summary>
        public static string BettingProjectST {
            get {
                return ResourceManager.GetString("BettingProjectST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto Project.
        /// </summary>
        public static string CryptoProject {
            get {
                return ResourceManager.GetString("CryptoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loved, volatile and complicated for a novice trader. We understand its potential and let the best traders on the market handle it all..
        /// </summary>
        public static string CryptoProjectST {
            get {
                return ResourceManager.GetString("CryptoProjectST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Project.
        /// </summary>
        public static string TradingProject {
            get {
                return ResourceManager.GetString("TradingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sector is now the race to who develops the fastest, most powerful and most performing A.I. We evaluate, test and offer only the best ones..
        /// </summary>
        public static string TradingProjectST {
            get {
                return ResourceManager.GetString("TradingProjectST", resourceCulture);
            }
        }
    }
}
