//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MazzaWebSite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MazzaWebSite.Resources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AboutUs1P {
            get {
                return ResourceManager.GetString("AboutUs1P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AboutUs2P {
            get {
                return ResourceManager.GetString("AboutUs2P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AboutUs3P {
            get {
                return ResourceManager.GetString("AboutUs3P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AboutUsST {
            get {
                return ResourceManager.GetString("AboutUsST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved.
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital Invested.
        /// </summary>
        public static string CapitalInvested {
            get {
                return ResourceManager.GetString("CapitalInvested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital Withdrawn.
        /// </summary>
        public static string CapitalWithdrawn {
            get {
                return ResourceManager.GetString("CapitalWithdrawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string Community {
            get {
                return ResourceManager.GetString("Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our main objective is to create a community of people that can talk and exchange new opportunities for profit.
        /// </summary>
        public static string CommunityST {
            get {
                return ResourceManager.GetString("CommunityST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diversify your earnings.
        /// </summary>
        public static string DiversifyEarnings {
            get {
                return ResourceManager.GetString("DiversifyEarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We offer various earning opportunities, so as to have different revenues and to bear the risk of loss of capital.
        /// </summary>
        public static string DiversifyEarningsST {
            get {
                return ResourceManager.GetString("DiversifyEarningsST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide&lt;br&gt;solutions&lt;br&gt;for your money!.
        /// </summary>
        public static string Motto {
            get {
                return ResourceManager.GetString("Motto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networking Possibility.
        /// </summary>
        public static string NetworkPossibility {
            get {
                return ResourceManager.GetString("NetworkPossibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We offer the opportunity to make you gain by letting our friends know about our reality.
        /// </summary>
        public static string NetworkPossibilityST {
            get {
                return ResourceManager.GetString("NetworkPossibilityST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Goals.
        /// </summary>
        public static string OurTarget {
            get {
                return ResourceManager.GetString("OurTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laudem latine persequeris id sed, ex fabulas delectus quo. No vel partiendo abhorreant vituperatoribus..
        /// </summary>
        public static string OurTargetST {
            get {
                return ResourceManager.GetString("OurTargetST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passive Icome.
        /// </summary>
        public static string PassiveIcome {
            get {
                return ResourceManager.GetString("PassiveIcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We offer the opportunity to make you earn without you moving a finger making you save time.
        /// </summary>
        public static string PassiveIcomeST {
            get {
                return ResourceManager.GetString("PassiveIcomeST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professionality.
        /// </summary>
        public static string Professionality {
            get {
                return ResourceManager.GetString("Professionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our team is composed by experts in the world of finance who guarantee a certain level of skills and efficiency.
        /// </summary>
        public static string ProfessionalityST {
            get {
                return ResourceManager.GetString("ProfessionalityST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuality.
        /// </summary>
        public static string Punctuality {
            get {
                return ResourceManager.GetString("Punctuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All profits will be transferred on time to all interested parties without interference or delays.
        /// </summary>
        public static string PunctualityST {
            get {
                return ResourceManager.GetString("PunctualityST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security &amp; Privacy.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All your data and movements will remain secreted and inviolate by any internal or external entity. 
        ///The best encryption level on the market is applied.
        /// </summary>
        public static string SecurityST {
            get {
                return ResourceManager.GetString("SecurityST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socials.
        /// </summary>
        public static string Socials {
            get {
                return ResourceManager.GetString("Socials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        public static string Strategy {
            get {
                return ResourceManager.GetString("Strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quality of the project comes from a scrupulous analysis of various opportunities for profit and efficiency of the latter.
        /// </summary>
        public static string StrategyST {
            get {
                return ResourceManager.GetString("StrategyST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency.
        /// </summary>
        public static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All info and movements will be accessible to anyone; to obtain the best functioning of this project, some of your transactions will be published, subject to prior authorization.
        /// </summary>
        public static string TransparencyST {
            get {
                return ResourceManager.GetString("TransparencyST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Invest with us?.
        /// </summary>
        public static string WhyInvestWithUs {
            get {
                return ResourceManager.GetString("WhyInvestWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WhyInvestWithUsST {
            get {
                return ResourceManager.GetString("WhyInvestWithUsST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Us.
        /// </summary>
        public static string WhyUs {
            get {
                return ResourceManager.GetString("WhyUs", resourceCulture);
            }
        }
    }
}
