//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MazzaWebSite.Connected_Services.EmailVerify
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.cdyne.com/", ConfigurationName="EmailVerify.EmailVerifySoap")]
    public interface EmailVerifySoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cdyne.com/VerifyMXRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int VerifyMXRecord(string email, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cdyne.com/VerifyMXRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<int> VerifyMXRecordAsync(string email, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cdyne.com/VerifyEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ReturnValues VerifyEmail(string email, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cdyne.com/VerifyEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<ReturnValues> VerifyEmailAsync(string email, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cdyne.com/VerifyEmailWithTimeout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ReturnValues VerifyEmailWithTimeout(string email, string timeout, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cdyne.com/VerifyEmailWithTimeout", ReplyAction="*")]
        System.Threading.Tasks.Task<ReturnValues> VerifyEmailWithTimeoutAsync(string email, string timeout, string LicenseKey);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cdyne.com/")]
    public partial class ReturnValues : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool validLicenseKeyField;
        
        private bool correctSyntaxField;
        
        private bool emailDomainFoundField;
        
        private bool emailDisposableField;
        
        private bool domainVerifiesEmailField;
        
        private bool domainAcceptsMailField;
        
        private bool emailVerifiedField;
        
        private bool timeoutField;
        
        private bool domainServersDownField;
        
        private bool goodEmailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool ValidLicenseKey {
            get {
                return this.validLicenseKeyField;
            }
            set {
                this.validLicenseKeyField = value;
                this.RaisePropertyChanged("ValidLicenseKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool CorrectSyntax {
            get {
                return this.correctSyntaxField;
            }
            set {
                this.correctSyntaxField = value;
                this.RaisePropertyChanged("CorrectSyntax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool EmailDomainFound {
            get {
                return this.emailDomainFoundField;
            }
            set {
                this.emailDomainFoundField = value;
                this.RaisePropertyChanged("EmailDomainFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool EmailDisposable {
            get {
                return this.emailDisposableField;
            }
            set {
                this.emailDisposableField = value;
                this.RaisePropertyChanged("EmailDisposable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool DomainVerifiesEmail {
            get {
                return this.domainVerifiesEmailField;
            }
            set {
                this.domainVerifiesEmailField = value;
                this.RaisePropertyChanged("DomainVerifiesEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool DomainAcceptsMail {
            get {
                return this.domainAcceptsMailField;
            }
            set {
                this.domainAcceptsMailField = value;
                this.RaisePropertyChanged("DomainAcceptsMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool EmailVerified {
            get {
                return this.emailVerifiedField;
            }
            set {
                this.emailVerifiedField = value;
                this.RaisePropertyChanged("EmailVerified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool Timeout {
            get {
                return this.timeoutField;
            }
            set {
                this.timeoutField = value;
                this.RaisePropertyChanged("Timeout");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool DomainServersDown {
            get {
                return this.domainServersDownField;
            }
            set {
                this.domainServersDownField = value;
                this.RaisePropertyChanged("DomainServersDown");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool GoodEmail {
            get {
                return this.goodEmailField;
            }
            set {
                this.goodEmailField = value;
                this.RaisePropertyChanged("GoodEmail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmailVerifySoapChannel : EmailVerifySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailVerifySoapClient : System.ServiceModel.ClientBase<EmailVerifySoap>, EmailVerifySoap {
        
        public EmailVerifySoapClient() {
        }
        
        public EmailVerifySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailVerifySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailVerifySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailVerifySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int VerifyMXRecord(string email, string LicenseKey) {
            return base.Channel.VerifyMXRecord(email, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<int> VerifyMXRecordAsync(string email, string LicenseKey) {
            return base.Channel.VerifyMXRecordAsync(email, LicenseKey);
        }
        
        public ReturnValues VerifyEmail(string email, string LicenseKey) {
            return base.Channel.VerifyEmail(email, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<ReturnValues> VerifyEmailAsync(string email, string LicenseKey) {
            return base.Channel.VerifyEmailAsync(email, LicenseKey);
        }
        
        public ReturnValues VerifyEmailWithTimeout(string email, string timeout, string LicenseKey) {
            return base.Channel.VerifyEmailWithTimeout(email, timeout, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<ReturnValues> VerifyEmailWithTimeoutAsync(string email, string timeout, string LicenseKey) {
            return base.Channel.VerifyEmailWithTimeoutAsync(email, timeout, LicenseKey);
        }
    }
}
